### ISSUE TITLE
Add support for psr/http-message v2

### ISSUE THREAD

**Issue by LordSimal** [jeromegamez/mite-php#9]
Hey there, fellow CakePHP core member here 😁 

We just released CakePHP 5 RC1 and with that we upgraded to https://github.com/php-fig/http-message/releases/tag/2.0 which added return types.

So this package would require a new, separate version to be released with those added return types and the adjusted composer requirement for `"psr/http-message": "^2.0"` so that future CakePHP 5 users (and of course other frameworks which require psr/http-message v2) can use this awesome package 😁

**Comment by jeromegamez** [comment]
Thank you for the kind words, I really appreciate it! 🥰

I included `psr/http-message` as direct dependency because the `ApiClient` class uses them and I usually try to avoid transitive dependencies.

But in this case, the dependency is always included thanks to `psr/http-client` and `psr/http-factory`... how would you feel about removing it from the `composer.json` file altogether and make it a minor release?

**Comment by LordSimal** [comment]
> how would you feel about removing it from the `composer.json` file altogether and make it a minor release?

this is fine by me as well 😁

**Comment by jeromegamez** [comment]
Done! https://github.com/jeromegamez/mite-php/releases/tag/3.1.0 🚀

**Comment by LordSimal** [comment]
Thank you!
